import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";

/**
 * The forwardable artifact: a one-page (plus overflow) license waste report
 * in the ledger style, rendered server-side with @react-pdf/renderer.
 */

const C = {
  canvas: "#fbfcfc",
  ink: "#0c1a17",
  inkSoft: "#3a4541",
  inkFaint: "#687772",
  line: "#e4eae8",
  brand: "#0f766e",
  waste: "#b45309",
};

const styles = StyleSheet.create({
  page: {
    backgroundColor: C.canvas,
    color: C.ink,
    padding: 48,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  wordmark: { fontSize: 16, fontFamily: "Times-Roman" },
  hRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    borderBottomWidth: 1,
    borderBottomColor: C.ink,
    paddingBottom: 10,
  },
  meta: { color: C.inkSoft, fontSize: 9, textAlign: "right" },
  kpiRow: { flexDirection: "row", marginTop: 18, gap: 10 },
  kpi: {
    flex: 1,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: "#ffffff",
    padding: 10,
  },
  kpiLabel: { fontSize: 7, color: C.inkFaint, textTransform: "uppercase", letterSpacing: 1 },
  kpiValue: { fontSize: 16, fontFamily: "Times-Roman", marginTop: 4 },
  section: {
    fontSize: 8,
    color: C.inkFaint,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    marginTop: 22,
    marginBottom: 6,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: C.line,
    paddingVertical: 5,
  },
  cellTitle: { flex: 1, paddingRight: 12 },
  cellImpact: { width: 90, textAlign: "right", color: C.waste },
  footer: {
    position: "absolute",
    bottom: 32,
    left: 48,
    right: 48,
    borderTopWidth: 1,
    borderTopColor: C.line,
    paddingTop: 8,
    fontSize: 7.5,
    color: C.inkFaint,
  },
});

export type ReportData = {
  tenantName: string;
  generatedOn: string;
  monthlySpend: string;
  monthlyWaste: string;
  annualWaste: string;
  openFindings: number;
  byRule: { label: string; count: number; impact: string }[];
  topFindings: { title: string; impact: string }[];
};

export const WasteReport = ({ data }: { data: ReportData }) => (
  <Document
    title={`License waste report: ${data.tenantName}`}
    author="LicenseMeter"
  >
    <Page size="A4" style={styles.page}>
      <View style={styles.hRow}>
        <View>
          <Text style={styles.wordmark}>
            License<Text style={{ color: C.brand }}>Meter</Text>
          </Text>
          <Text style={{ color: C.inkSoft, marginTop: 4 }}>
            License waste report
          </Text>
        </View>
        <View>
          <Text style={styles.meta}>{data.tenantName}</Text>
          <Text style={styles.meta}>{data.generatedOn} · 90-day window</Text>
        </View>
      </View>

      <View style={styles.kpiRow}>
        <View style={styles.kpi}>
          <Text style={styles.kpiLabel}>Monthly spend</Text>
          <Text style={styles.kpiValue}>{data.monthlySpend}</Text>
        </View>
        <View style={styles.kpi}>
          <Text style={styles.kpiLabel}>Monthly waste</Text>
          <Text style={[styles.kpiValue, { color: C.waste }]}>
            {data.monthlyWaste}
          </Text>
        </View>
        <View style={styles.kpi}>
          <Text style={styles.kpiLabel}>Annualized waste</Text>
          <Text style={[styles.kpiValue, { color: C.waste }]}>
            {data.annualWaste}
          </Text>
        </View>
        <View style={styles.kpi}>
          <Text style={styles.kpiLabel}>Open findings</Text>
          <Text style={styles.kpiValue}>{String(data.openFindings)}</Text>
        </View>
      </View>

      <Text style={styles.section}>Waste by rule</Text>
      {data.byRule.map((r) => (
        <View key={r.label} style={styles.row}>
          <Text style={styles.cellTitle}>
            {r.label} ({r.count})
          </Text>
          <Text style={styles.cellImpact}>{r.impact}</Text>
        </View>
      ))}

      <Text style={styles.section}>Largest findings</Text>
      {data.topFindings.map((f, i) => (
        <View key={i} style={styles.row}>
          <Text style={styles.cellTitle}>{f.title}</Text>
          <Text style={styles.cellImpact}>{f.impact}</Text>
        </View>
      ))}

      <View style={styles.footer} fixed>
        <Text>
          Generated by LicenseMeter (www.licensemeter.com) from read-only
          Microsoft Graph metadata. Impact figures use the workspace price
          book; monthly amounts assume current assignments. Findings marked
          acknowledged are included until resolved.
        </Text>
      </View>
    </Page>
  </Document>
);
